- id: poetry-export
  name: Poetry requirements.txt exporter
  description: Runs 'poetry export' to automatically export a 'requirements.txt' file.
  language: script
  entry: poetry-export.sh
  files: "^poetry.lock$"
  pass_filenames: false


